version: "3.8"

# add the serivces needed (postgres,go)
services:
  postgres:
    container_name: postgres
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: task_tracker
    ports:
      - "5435:5435"
    volumes:
      - dbdata:/var/lib/postgresql/data

  go:
    container_name: go
    build:
      context: .
    depends_on:
      - "postgres"

volumes:
  dbdata: